# Generated by Django 6.0.1 on 2026-04-28 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('es_adr', models.BooleanField(default=False, help_text='Seleccione si el cargo es exclusivo de ADR', verbose_name='Es cargo de ADR')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la categoría (tipo). Ej: Televisor, All in One, Monitor, Laptop, etc.', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('usa_netbios', models.BooleanField(default=False, help_text='Marque si los equipos de esta categoría se unen al dominio.', verbose_name='¿Requiere NetBIOS?')),
                ('usa_bdo', models.BooleanField(default=True, help_text='Marque si a estos equipos se les pega placa de inventario.', verbose_name='¿Requiere BDO?')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del Edificio', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del estado', max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la marca', max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CRE', 'Creación'), ('MOD', 'Modificación'), ('ELI', 'Eliminación'), ('RES', 'Restauración')], max_length=3, verbose_name='Acción Realizada')),
                ('object_id', models.PositiveIntegerField()),
                ('campo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo Editado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsable')),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Detalle (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/imagen/main/', verbose_name='Imagen (opcional)')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='productos/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='productos/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Seleccione la categoría correspondiente', on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria', verbose_name='Categoría (tipo)')),
                ('marca', models.ForeignKey(help_text='Seleccione la marca correspondiente', on_delete=django.db.models.deletion.PROTECT, to='inventario.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Catálogo de producto',
                'verbose_name_plural': 'Catálogo de productos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.areaadministrativa', verbose_name='Área administrativa')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del Piso/Nivel', max_length=20, verbose_name='Piso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('edificio', models.ForeignKey(help_text='Seleccione el edificio correspondiente', on_delete=django.db.models.deletion.PROTECT, to='inventario.edificio', verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese de la ubicación (sala, bodega, pasillo, etc.)', max_length=100, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ubicaciones/imagen/main', verbose_name='Imagen de la ubicación')),
                ('imagen_thumb_medium', models.ImageField(blank=True, editable=False, null=True, upload_to='ubicaciones/imagen/medium/', verbose_name='Thumbnail (600x600)')),
                ('imagen_thumb_small', models.ImageField(blank=True, editable=False, null=True, upload_to='ubicaciones/imagen/small/', verbose_name='Thumbnail (50x50)')),
                ('piso', models.ForeignKey(help_text='Seleccione el piso/nivel correspondiente', on_delete=django.db.models.deletion.PROTECT, to='inventario.piso', verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='MapeoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255, unique=True, verbose_name='Ubicación Original (Texto Sucio)')),
                ('revisado', models.BooleanField(default=False, verbose_name='Validado por humano')),
                ('ubicacion_nueva', models.ForeignKey(blank=True, help_text='Seleccione la ubicación real a la que corresponde el texto original.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacion', verbose_name='Ubicación Estandarizada')),
            ],
            options={
                'verbose_name': 'Mapeo de Ubicación',
                'verbose_name_plural': 'Mapeos de Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, help_text='Ingrese el número de serie del equipo', max_length=50, null=True, verbose_name='N° de serie')),
                ('etiqueta', models.CharField(blank=True, help_text='Ingrese el código de la etiqueta del equipo', max_length=50, null=True, verbose_name='Etiqueta')),
                ('bdo', models.CharField(blank=True, help_text='Ingrese el número BDO del equipo', max_length=50, null=True, verbose_name='Número BDO')),
                ('netbios', models.CharField(blank=True, help_text='Ingrese el código NetBios del equipo', max_length=50, null=True, verbose_name='Código NetBios')),
                ('tipo_uso', models.CharField(choices=[('PER', 'Personal/Oficina'), ('LAB', 'Laboratorio/Sala'), ('EVE', 'Eventos'), ('ACA', 'Académico'), ('ADM', 'Administrativo'), ('OTR', 'Otro')], default='PER', help_text='Define si el equipo es de uso regular, de laboratorio o reservado para eventos', max_length=3, verbose_name='Propósito / Tipo de Uso')),
                ('tipo_red', models.CharField(choices=[('DOM', 'Red Institucional (Dominio)'), ('ISLA', 'Equipo Isla'), ('LAB', 'Laboratorio Aislado'), ('OTRO', 'Otro / Sin Red')], default='DOM', max_length=4, verbose_name='Tipo de Conexión/Red')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('catalogo', models.ForeignKey(help_text='Seleccione el producto correspondiente', on_delete=django.db.models.deletion.PROTECT, to='inventario.catalogo', verbose_name='Catálogo')),
                ('estado', models.ForeignKey(help_text='Seleccione el estado correspondiente', on_delete=django.db.models.deletion.PROTECT, to='inventario.estado', verbose_name='Estado')),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Seleccionar persona responsable del equipo', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.funcionario', verbose_name='Asignatario')),
                ('ubicacion', models.ForeignKey(blank=True, help_text='Seleccionar ubicación donde se encuentra el equipo', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'permissions': [('view_activo', 'Ver activos del sistema'), ('add_activo', 'Agregar nuevos activos'), ('change_activo', 'Modificar información de los activos'), ('deactivate_activo', 'Dar de baja activos (Cambiar estado)'), ('delete_activo', 'Eliminar activos')],
                'default_permissions': [],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogo',
            constraint=models.UniqueConstraint(fields=('categoria', 'marca', 'modelo'), name='unique_catalogo_producto'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(('bdo__isnull', False), ('is_deleted', False)), fields=('bdo',), name='unique_bdo_activos'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(('etiqueta__isnull', False), ('is_deleted', False)), fields=('etiqueta',), name='unique_etiqueta_activos'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('numero_serie__isnull', False)), fields=('numero_serie',), name='unique_nserie_activos'),
        ),
    ]
