# Generated by Django 6.0.1 on 2026-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/imagen/main', verbose_name='Imagen representativa'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_thumb_medium',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='categorias/imagen/medium/', verbose_name='Thumbnail (600x600)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_thumb_small',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='categorias/imagen/small/', verbose_name='Thumbnail (50x50)'),
        ),
    ]
