# Generated by Django 6.0.1 on 2026-05-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_imagen_categoria_imagen_thumb_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaadministrativa',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sigla'),
        ),
    ]
