# Generated by Django 6.0.1 on 2026-05-28 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_areaadministrativa_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='acta_devolucion',
            field=models.FileField(blank=True, help_text='Suba el acta de devolución escaneada en formato PDF', null=True, upload_to='documentos/actas/devoluciones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Acta de Devolución'),
        ),
        migrations.AddField(
            model_name='activo',
            name='acta_entrega',
            field=models.FileField(blank=True, help_text='Suba el acta de entrega escaneada en formato PDF', null=True, upload_to='documentos/actas/entregas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Acta de Entrega'),
        ),
    ]
