# Generated by Django 6.0.1 on 2026-06-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_activo_acta_devolucion_activo_acta_entrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaadministrativa',
            options={'verbose_name': 'Área Administrativa', 'verbose_name_plural': 'Áreas Administrativas'},
        ),
    ]
