# Generated by Django 6.0.1 on 2026-09-16 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_areaadministrativa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaadministrativa',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Error: Este campo solo admite letras y espacios. No se permiten números ni caracteres especiales (ej: #, @, !).', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='areaadministrativa',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Error: Este campo solo admite letras, números y guiones medios. No ingrese espacios ni caracteres especiales.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='Sigla'),
        ),
    ]
