# Generated by Django 6.0.1 on 2026-09-17 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_areaadministrativa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ingrese el nombre', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='bdo',
            field=models.CharField(blank=True, help_text='Ingrese el número BDO del equipo', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Este campo debe contener estrictamente números enteros.', regex='^\\d+$')], verbose_name='Número BDO'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Ingrese el código de la etiqueta del equipo', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números y guiones medios. Sin espacios.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='netbios',
            field=models.CharField(blank=True, help_text='Ingrese el código NetBios del equipo', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números y guiones medios. Sin espacios.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='Código NetBios'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Ingrese el número de serie del equipo', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números y guiones medios. Sin espacios.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='N° de serie'),
        ),
        migrations.AlterField(
            model_name='areaadministrativa',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras y espacios. Sin números ni caracteres especiales.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='areaadministrativa',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números y guiones medios. Sin espacios.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras y espacios. Sin números ni caracteres especiales.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (como <, >, {, }).', regex='^[^<>{}]+$')], verbose_name='Detalle (opcional)'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (como <, >, {, }).', regex='^[^<>{}]+$')], verbose_name='Descripción (opcional)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre de la categoría (tipo). Ej: Televisor, All in One, Monitor, Laptop, etc.', max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (como <, >, {, }).', regex='^[^<>{}]+$')], verbose_name='Descripción (opcional)'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del Edificio', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (como <, >, {, }).', regex='^[^<>{}]+$')], verbose_name='Descripción (opcional)'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del estado', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras y espacios. Sin números ni caracteres especiales.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras y espacios. Sin números ni caracteres especiales.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono no válido. Use solo números y un "+" opcional (Ej: +56912345678).', regex='^\\+?56?\\d{9}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre de la marca', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='piso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (como <, >, {, }).', regex='^[^<>{}]+$')], verbose_name='Descripción (opcional)'),
        ),
        migrations.AlterField(
            model_name='piso',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del Piso/Nivel', max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (como <, >, {, }).', regex='^[^<>{}]+$')], verbose_name='Descripción (opcional)'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(help_text='Ingrese de la ubicación (sala, bodega, pasillo, etc.)', max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Ubicación'),
        ),
    ]
