# Generated by Django 6.0.1 on 2026-09-21 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_activo_nombre_alter_activo_bdo_alter_activo_etiqueta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='activo',
            name='nombre_proyector',
            field=models.CharField(blank=True, help_text='Ingrese el nombre configurado mediante el control remoto', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Nombre en Red (Control Remoto)'),
        ),
        migrations.AddField(
            model_name='activo',
            name='red_proyector',
            field=models.CharField(blank=True, choices=[('ACA', 'Académico'), ('ADM', 'Administrativo')], help_text='Seleccione la red asociada (académica o administrativa)', max_length=3, null=True, verbose_name='Red del Proyector'),
        ),
    ]
