# Generated by Django 6.0.1 on 2026-09-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_activo_nombre_activo_nombre_proyector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='red_proyector',
        ),
    ]
