# Generated by Django 6.0.1 on 2026-09-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_activo_red_proyector'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='conexion_proyector',
            field=models.CharField(blank=True, choices=[('WIFI', 'Inalámbrica (Wi-Fi)'), ('ETH', 'Cableada (Ethernet/UTP)'), ('OTR', 'Otra / Sin conexión')], help_text='Seleccione cómo se conecta el proyector a la red', max_length=4, null=True, verbose_name='Medio de Conexión'),
        ),
    ]
