# Generated by Django 6.0.1 on 2026-09-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_areaadministrativa_nombre_and_more'),
        ('inventario', '0009_activo_conexion_proyector'),
    ]

    operations = [
    ]
