# Generated by Django 6.0.1 on 2026-09-28 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_merge_20260927_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaadministrativa',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras y espacios. Sin números ni caracteres especiales.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='areaadministrativa',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números y guiones medios. Sin espacios.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='Sigla'),
        ),
    ]
