# Generated by Django 6.0.1 on 2026-10-02 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_areaadministrativa_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='netbios',
            field=models.CharField(blank=True, help_text='Ingrese el código NetBios del equipo', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, guiones y guiones bajos. Sin espacios.', regex='^[a-zA-Z0-9_\\-]+$')], verbose_name='Código NetBios'),
        ),
    ]
