# Generated by Django 6.0.1 on 2026-09-15 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_alter_areaadministrativa_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, help_text='Vacío si el ciclo fue creado automáticamente por el comando mensual programado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Ciclo de Revisión',
                'verbose_name_plural': 'Ciclos de Revisión',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='EquipoMantenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROY', 'Proyector'), ('IMPR', 'Impresora')], max_length=4, verbose_name='Tipo de equipo')),
                ('activo_en_revision', models.BooleanField(default=True, help_text='Desmárquelo para pausar este equipo sin perder su historial. El registro nunca se elimina.', verbose_name='Incluido en revisión mensual')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_mantenible', to='inventario.activo', verbose_name='Activo')),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
            ],
            options={
                'verbose_name': 'Equipo en Mantención',
                'verbose_name_plural': 'Equipos en Mantención',
            },
        ),
        migrations.CreateModel(
            name='RevisionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('OK', 'OK'), ('NOV', 'Con Novedad')], default='PEN', max_length=3)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario / Novedad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to='mantencion.ciclorevision')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to='mantencion.equipomantenible')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('ubicacion_en_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Revisión de Equipo',
                'verbose_name_plural': 'Revisiones de Equipos',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mantencion/evidencias/%Y/%m/', verbose_name='Evidencia')),
                ('tipo_archivo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Video')], max_length=5)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='mantencion.revisionequipo')),
            ],
            options={
                'verbose_name': 'Evidencia de Revisión',
                'verbose_name_plural': 'Evidencias de Revisión',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='ciclorevision',
            constraint=models.UniqueConstraint(fields=('anio', 'mes'), name='unique_ciclo_anio_mes'),
        ),
        migrations.AddConstraint(
            model_name='revisionequipo',
            constraint=models.UniqueConstraint(fields=('ciclo', 'equipo'), name='unique_revision_ciclo_equipo'),
        ),
    ]
