# Generated by Django 6.0.1 on 2026-09-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0002_ciclo_por_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclorevision',
            options={'ordering': ['-fecha_inicio', '-fecha_generado', '-id'], 'verbose_name': 'Ciclo de Revisión', 'verbose_name_plural': 'Ciclos de Revisión'},
        ),
    ]
