# Generated by Django 6.0.1 on 2026-09-17 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_areaadministrativa_nombre_and_more'),
        ('mantencion', '0003_alter_ciclorevision_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomantenible',
            name='activo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipo_mantenible', to='inventario.activo', verbose_name='Activo (proyectores)'),
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='HP', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('tipo_impresion', models.CharField(blank=True, help_text='Ej: Blanco y Negro, Color', max_length=30, verbose_name='Tipo de impresión')),
                ('rango_impresiones', models.CharField(blank=True, max_length=30, verbose_name='Rango de impresiones contratado')),
                ('nombre_equipo', models.CharField(blank=True, help_text='Hostname asignado por el proveedor, ej: IQQ_E540_BODEGA', max_length=100, verbose_name='Nombre de red')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='N° de Serie')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP')),
                ('mac', models.CharField(blank=True, max_length=17, verbose_name='MAC')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código del proveedor')),
                ('estado', models.CharField(choices=[('OPER', 'Operativa'), ('BAJA', 'De Baja / Deprecada')], default='OPER', max_length=4, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregada por')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
                'ordering': ['modelo', 'nombre_equipo'],
            },
        ),
        migrations.AddField(
            model_name='equipomantenible',
            name='impresora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipo_mantenible', to='mantencion.impresora', verbose_name='Impresora'),
        ),
        migrations.AddConstraint(
            model_name='equipomantenible',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activo__isnull', False), ('impresora__isnull', True), ('tipo', 'PROY')), models.Q(('activo__isnull', True), ('impresora__isnull', False), ('tipo', 'IMPR')), _connector='OR'), name='equipo_mantenible_un_solo_dueno'),
        ),
    ]
