# Generated by Django 6.0.1 on 2026-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0004_alter_equipomantenible_activo_impresora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código del proveedor'),
        ),
    ]
