# Generated by Django 6.0.1 on 2026-09-23 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0005_alter_impresora_codigo_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('REV_OK', 'Revisión marcada OK'), ('REV_NOV', 'Revisión con novedad'), ('ENROQUE', 'Enroque (cambio de ubicación)'), ('EQ_ALTA', 'Equipo agregado al roster'), ('EQ_PAUSA', 'Equipo pausado'), ('EQ_REACT', 'Equipo reactivado'), ('IMP_ALTA', 'Impresora agregada'), ('IMP_BAJA', 'Impresora dada de baja')], max_length=10, verbose_name='Acción')),
                ('tipo_equipo', models.CharField(blank=True, choices=[('PROY', 'Proyector'), ('IMPR', 'Impresora')], max_length=4, null=True, verbose_name='Tipo de equipo')),
                ('equipo_descripcion', models.CharField(max_length=200, verbose_name='Equipo afectado')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
