# Generated by Django 6.0.1 on 2026-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0006_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionequipo',
            name='sigue_operativo',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Sigue operativo pese a la novedad?'),
        ),
    ]
