# Generated by Django 6.0.1 on 2026-09-29 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0007_revisionequipo_sigue_operativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Este campo debe contener estrictamente números enteros.', regex='^\\d+$')], verbose_name='Código del proveedor'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='mac',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Formato de MAC no válido (use solo dígitos hexadecimales, con o sin separadores).', regex='^[0-9A-Fa-f]{2}([:\\-]?[0-9A-Fa-f]{2}){5}$')], verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='marca',
            field=models.CharField(default='HP', max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='modelo',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números y guiones medios. Sin espacios.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='nombre_equipo',
            field=models.CharField(blank=True, help_text='Hostname asignado por el proveedor, ej: IQQ_E540_BODEGA', max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, guiones y guiones bajos. Sin espacios.', regex='^[a-zA-Z0-9_\\-]+$')], verbose_name='Nombre de red'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='numero_serie',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números y guiones medios. Sin espacios.', regex='^[a-zA-Z0-9\\-]+$')], verbose_name='N° de Serie'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='rango_impresiones',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Rango de impresiones contratado'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='tipo_impresion',
            field=models.CharField(blank=True, help_text='Ej: Blanco y Negro, Color', max_length=30, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras, números, espacios, guiones y puntos.', regex='^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s\\-\\.]+$')], verbose_name='Tipo de impresión'),
        ),
    ]
