# Generated by Django 6.0.1 on 2026-09-30 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0008_alter_impresora_codigo_proveedor_alter_impresora_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='ip_automatica',
            field=models.BooleanField(default=False, help_text='Márquelo si la IP la asigna el router automáticamente (no tiene IP fija).', verbose_name='Automático (DHCP)'),
        ),
        migrations.AlterField(
            model_name='impresora',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El texto contiene caracteres no permitidos (como <, >, {, }).', regex='^[^<>{}]+$')], verbose_name='IP'),
        ),
    ]
