# Generated by Django 6.0.1 on 2026-10-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0009_impresora_ip_automatica_alter_impresora_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='tipo_impresion',
            field=models.CharField(blank=True, choices=[('Blanco y Negro', 'Blanco y Negro'), ('Color', 'Color')], max_length=30, verbose_name='Tipo de impresión'),
        ),
    ]
