# Generated by Django 5.0.8 on 2025-12-16 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0041_alter_equiposisla_options_remove_equiposisla_unive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equiposisla',
            options={'ordering': ['ubicacion', '-fecha_creacion'], 'verbose_name': 'Equipo Isla', 'verbose_name_plural': 'Equipos Islas'},
        ),
        #migrations.AddField(
        #    model_name='eliminados',
        #    name='etiqueta',
        #    field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        #),
        migrations.AlterField(
            model_name='equiposisla',
            name='activo',
            field=models.CharField(default='Equipos Isla', max_length=150, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrador por'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
        migrations.AlterField(
            model_name='equiposisla',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterModelTable(
            name='equiposisla',
            table=None,
        ),
        migrations.CreateModel(
            name='SwitchDeRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie')),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta')),
                ('bdo', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='Marca')),
                ('ubicacion', models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('netbios', models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrador por')),
            ],
            options={
                'verbose_name': 'Switch De Red',
                'verbose_name_plural': 'Switches De Redes',
                'ordering': ['ubicacion', '-fecha_creacion'],
                'indexes': [models.Index(fields=['creado_por'], name='idx_switchdered_creado_por')],
            },
        ),
    ]
