# Generated by Django 6.0.1 on 2026-04-13 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0044_allinone_verbose_name_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminados',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AddIndex(
            model_name='equiposisla',
            index=models.Index(fields=['creado_por'], name='idx_equiposisla_creado_por'),
        ),
    ]
