# Generated by Django 6.0.1 on 2026-04-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0046_areaadministrativa_cargo_categoria_edificio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo_red',
            field=models.CharField(choices=[('DOM', 'Red Institucional (Dominio)'), ('ISLA', 'Equipo Isla'), ('LAB', 'Laboratorio Aislado'), ('OTRO', 'Otro / Sin Red')], default='DOM', max_length=4, verbose_name='Tipo de Conexión/Red'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(('bdo__isnull', False), ('is_deleted', False)), fields=('bdo',), name='unique_bdo_activos'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(('etiqueta__isnull', False), ('is_deleted', False)), fields=('etiqueta',), name='unique_etiqueta_activos'),
        ),
    ]
