# Generated by Django 6.0.1 on 2026-04-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0047_activo_is_deleted_activo_tipo_red_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='usa_bdo',
            field=models.BooleanField(default=True, help_text='Marque si a estos equipos se les pega placa de inventario.', verbose_name='¿Requiere BDO?'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usa_netbios',
            field=models.BooleanField(default=False, help_text='Marque si los equipos de esta categoría se unen al dominio.', verbose_name='¿Requiere NetBIOS?'),
        ),
    ]
