# Generated by Django 6.0.1 on 2026-04-16 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0048_categoria_usa_bdo_categoria_usa_netbios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(help_text='Seleccionar ubicación donde se encuentra el equipo', on_delete=django.db.models.deletion.PROTECT, to='adr.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.CreateModel(
            name='MapeoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255, unique=True, verbose_name='Ubicación Original (Texto Sucio)')),
                ('revisado', models.BooleanField(default=False, verbose_name='Validado por humano')),
                ('ubicacion_nueva', models.ForeignKey(blank=True, help_text='Seleccione la ubicación real a la que corresponde el texto original.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adr.ubicacion', verbose_name='Ubicación Estandarizada')),
            ],
            options={
                'verbose_name': 'Mapeo de Ubicación',
                'verbose_name_plural': 'Mapeos de Ubicaciones',
            },
        ),
    ]
