# Generated by Django 6.0.1 on 2026-04-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0049_alter_activo_ubicacion_mapeoubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(help_text='Ingrese de la ubicación (sala, bodega, pasillo, etc.)', max_length=100, verbose_name='Ubicación'),
        ),
    ]
