# Generated by Django 6.0.1 on 2026-04-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0050_alter_ubicacion_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'verbose_name': 'Catálogo de producto', 'verbose_name_plural': 'Catálogo de productos'},
        ),
    ]
