# Generated by Django 6.0.1 on 2026-04-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0051_alter_catalogo_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('numero_serie__isnull', False)), fields=('numero_serie',), name='unique_nserie_activos'),
        ),
    ]
