# Generated by Django 6.0.1 on 2026-04-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0052_activo_unique_nserie_activos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipo_uso',
            field=models.CharField(choices=[('PER', 'Personal/Oficina'), ('LAB', 'Laboratorio/Sala'), ('EVE', 'Eventos'), ('ACA', 'Académico'), ('ADM', 'Administrativo'), ('OTR', 'Otro')], default='PER', help_text='Define si el equipo es de uso regular, de laboratorio o reservado para eventos', max_length=3, verbose_name='Propósito / Tipo de Uso'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Seleccionar ubicación donde se encuentra el equipo', null=True, on_delete=django.db.models.deletion.PROTECT, to='adr.ubicacion', verbose_name='Ubicación'),
        ),
    ]
