# Generated by Django 6.0.1 on 2026-04-23 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0053_alter_activo_tipo_uso_alter_activo_ubicacion'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CRE', 'Creación'), ('MOD', 'Modificación'), ('ELI', 'Eliminación (Soft Delete)'), ('RES', 'Restauración')], max_length=3, verbose_name='Acción Realizada')),
                ('object_id', models.PositiveIntegerField()),
                ('campo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo Editado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddConstraint(
            model_name='catalogo',
            constraint=models.UniqueConstraint(fields=('categoria', 'marca', 'modelo'), name='unique_catalogo_producto'),
        ),
        migrations.AddField(
            model_name='auditoriaactivo',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditoriaactivo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsable'),
        ),
    ]
