# Generated by Django 6.0.1 on 2026-04-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0054_auditoriaactivo_activo_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaactivo',
            name='accion',
            field=models.CharField(choices=[('CRE', 'Creación'), ('MOD', 'Modificación'), ('ELI', 'Eliminación'), ('RES', 'Restauración')], max_length=3, verbose_name='Acción Realizada'),
        ),
    ]
