# Generated by Django 6.0.1 on 2026-05-09 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0056_remove_activo_unique_bdo_activos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Docente/Funcionario')),
                ('docente_rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('sala', models.CharField(max_length=50, verbose_name='Sala / Ubicación')),
                ('item_prestado', models.CharField(choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Cable HDMI', 'Cable HDMI'), ('Alargador', 'Alargador / Zapatilla'), ('Adaptador Tipo C a HDMI', 'Adaptador Tipo C a HDMI'), ('Adaptador VGA a HDMI', 'Adaptador VGA a HDMI'), ('Puntero Presentador', 'Puntero / Presentador'), ('Control AC', 'Control Aire Acondicionado'), ('Otro', 'Otro (Especificar en observaciones)')], max_length=100, verbose_name='Ítem Prestado')),
                ('estado', models.CharField(choices=[('En Préstamo', 'En Préstamo'), ('Devuelto', 'Devuelto')], default='En Préstamo', max_length=50, verbose_name='Estado')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
