# Generated by Django 6.0.1 on 2026-05-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0058_alter_prestamo_item_prestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='item_prestado',
            field=models.CharField(choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Cable HDMI', 'Cable HDMI'), ('Alargador', 'Alargador / Zapatilla'), ('Adaptador Tipo C a HDMI', 'Adaptador Tipo C a HDMI'), ('Adaptador VGA a HDMI', 'Adaptador VGA a HDMI'), ('Puntero Presentador PPT', 'Puntero / Presentador PPT'), ('Otro', 'Otro (Especificar en observaciones)')], max_length=100, verbose_name='Ítem Prestado'),
        ),
    ]
