# Generated by Django 6.0.1 on 2026-05-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0059_alter_prestamo_item_prestado'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='allinone',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='allinoneadmins',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='audio',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='azotea',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='bodegaadr',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='eliminados',
        #    name='eliminado_por',
        #),
        #migrations.RemoveIndex(
        #    model_name='equiposisla',
        #    name='idx_equiposisla_creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='historialcambios',
        #    name='usuario',
        #),
        #migrations.RemoveField(
        #    model_name='minipc',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='monitor',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='notebook',
        #    name='creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='proyectores',
        #    name='creado_por',
        #),
        #migrations.RemoveIndex(
        #    model_name='switchdered',
        #    name='idx_switchdered_creado_por',
        #),
        #migrations.RemoveField(
        #    model_name='tablet',
        #    name='creado_por',
        #),
        #migrations.RemoveIndex(
        #    model_name='televisor',
        #    name='idx_televisor_creado_por',
        #),
        migrations.DeleteModel(
            name='AllInOne',
        ),
        migrations.DeleteModel(
            name='AllInOneAdmins',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Azotea',
        ),
        migrations.DeleteModel(
            name='BodegaADR',
        ),
        migrations.DeleteModel(
            name='Eliminados',
        ),
        #migrations.RemoveField(
        #    model_name='equiposisla',
        #    name='creado_por',
        #),
        migrations.DeleteModel(
            name='HistorialCambios',
        ),
        migrations.DeleteModel(
            name='MiniPC',
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Proyectores',
        ),
        #migrations.RemoveField(
        #    model_name='switchdered',
        #    name='creado_por',
        #),
        migrations.DeleteModel(
            name='Tablet',
        ),
        #migrations.RemoveField(
        #    model_name='televisor',
        #    name='creado_por',
        #),
        migrations.DeleteModel(
            name='EquiposIsla',
        ),
        migrations.DeleteModel(
            name='SwitchDeRed',
        ),
        migrations.DeleteModel(
            name='Televisor',
        ),
    ]
