# Generated by Django 6.0.1 on 2026-04-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
    ]