# Generated by Django 6.0.1 on 2026-10-02 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_ingresado', models.CharField(max_length=150, verbose_name='Usuario ingresado')),
                ('resultado', models.CharField(choices=[('OK', 'Acceso exitoso'), ('PASS', 'Contraseña incorrecta'), ('INACTIVA', 'Cuenta desactivada'), ('BLOQUEADA', 'Cuenta bloqueada (intentos fallidos)'), ('NOEXISTE', 'Usuario no existe')], max_length=10, verbose_name='Resultado')),
                ('portal', models.CharField(choices=[('INV', 'Inventario'), ('MANT', 'Mantención')], max_length=4, verbose_name='Portal')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
                'ordering': ['-fecha'],
            },
        ),
    ]
