"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os 
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =  config('DEBUG',cast=bool)
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']
LOGIN_REDIRECT_URL = '/inicio'
LOGOUT_REDIRECT_URL = '/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'django_browser_reload',
    'crispy_forms',
    'crispy_tailwind',
    'adr',
    'accounts.apps.AccountsConfig',
    'core',
]


X_FRAME_OPTIONS = "SAMEORIGIN"

TAILWIND_APP_NAME = 'theme'

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"

CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'adr.middleware.CurrentUserMiddleware',
    'accounts.middleware.AccountsCurrentUserMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',

]



ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         "DIRS": [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "core.context_processors.group_and_user",
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME').strip(),
        'USER': config('DB_USER').strip(),
        'PASSWORD': config('DB_PASSWORD').strip(),
        'HOST': config('DB_HOST').strip(),
        'PORT': config('DB_PORT', default='3306').strip(),
        'OPTIONS': {
            'connect_timeout': 10,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
     "OPTIONS": {"min_length": 12}},   # ← antes 8, ahora 12
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Carpeta(s) donde Django buscará los archivos “en crudo”
STATICFILES_DIRS = [
    
    os.path.join(BASE_DIR, 'static'),
   
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Configuración de Cloudinary
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME').strip(),
    api_key=config('CLOUDINARY_API_KEY').strip(),
    api_secret=config('CLOUDINARY_API_SECRET').strip(),
    secure=True
)

# Django 5.x usa STORAGES en lugar de DEFAULT_FILE_STORAGE
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Configuración explícita para django-cloudinary-storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME').strip(),
    'API_KEY': config('CLOUDINARY_API_KEY').strip(),
    'API_SECRET': config('CLOUDINARY_API_SECRET').strip(),
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
    },
}


# Email



if DEBUG:
    # En desarrollo, imprime el correo en la terminal y evita timeouts SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Producción: detectar automáticamente SendGrid o Gmail
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_TIMEOUT = 30

    _sendgrid_key = config('SENDGRID_API_KEY', default='')
    if _sendgrid_key:
        # Render: Usar SendGrid para notificaciones de cambios
        EMAIL_HOST = 'smtp.sendgrid.net'
        EMAIL_HOST_USER = 'apikey'
        EMAIL_HOST_PASSWORD = _sendgrid_key
        DEFAULT_FROM_EMAIL = config('EMAIL_FROM', default='iquiquepracticantes@gmail.com')
    else:
        # GitHub Actions: Usar Gmail SMTP para reporte semanal
        EMAIL_HOST = 'smtp.gmail.com'
        EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='iquiquepracticantes@gmail.com')
        EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
        DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

    SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Lista de destinatarios del reporte semanal
# Soporta variable de entorno (string separado por comas) o lista por defecto
_email_recipients_env = config('EMAIL_RECIPIENTS', default='')
if _email_recipients_env:
    # Si viene de variable de entorno (GitHub Actions), separar por comas
    EMAIL_RECIPIENTS = [email.strip() for email in _email_recipients_env.split(',')]
else:
    # Fallback a lista hardcodeada (para desarrollo local)
    EMAIL_RECIPIENTS = [
        'wtapia@inacap.cl',
        'hleris@inacap.cl',
        #'mvergarao@inacap.cl',
        #'jhonorato@inacap.cl',
        #'enavarrom@inacap.cl',
        #'algonzalezv@inacap.cl',
    ]
# Parámetros de seguridad para el login
LOGIN_FAILED_THRESHOLD = 3         # intentos fallidos para alertar
LOGIN_FAILED_WINDOW_SECONDS = 900  # ventana de 15 min para el conteo (ajústalo)
LOGIN_LOCK_SECONDS = 60

# (opcional) carpeta donde guardar temporales de backup
BACKUP_DIR = config('BACKUP_DIR', default=os.path.join(BASE_DIR, 'backups'))

PASSWORD_RESET_TIMEOUT = 60 * 60       # (opcional) 1 hora de validez del link
